### ISSUE TITLE
Initial Bootstrap setup

### ISSUE THREAD

**Issue by gautamrege** [joshsoftware/lightair#1]
- Rails 4.1.x 
- Ruby 2.1.x 
- MongoDB 2.6

Gems: (apart from the usual suspects)

```
`google_drive`  # Getting contacts from Web sources
`linkedin`          #  Getting contacts from Web sources
`sidekiq`           # Background jobs
`sendgrid`        # Sending mass mailer SMTP service
`twitter-bootstrap`
`mongoid`        # from github master
`devise`           # Only Email sign-up for invited users.
`devise_invitable`
# Need to investigate a good simple JS editor for Newsletter template.
```

**Comment by gautamrege** [comment]
- Default layout has not been set: app/layouts/application.html.haml
- bootstrap not added in app/assets/javascripts/application.js
- boostrap not added in app/assets/stylesheets folder.

Please get this done before I can close  this ticket.

**Comment by kanhaiyasharma007** [comment]
Done.
